import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './(components)/NavBar/NavBar'
import PropsProvider from './actions/consumProps'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css'
        ></link>
      </head>

      <body className={inter.className}>
        <PropsProvider>
          <NavBar />
          {children}
        </PropsProvider>
      </body>
    </html>
  )
}
